import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "../componets/navbar";
import { UserProvider } from "@/componets/store/ContexApi";
import { GoogleOAuthProvider } from '@react-oauth/google';
import Chatbot from "@/componets/chatBot/Chatbot";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <UserProvider>
          <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}>
            <NavBar />
            <Chatbot />
          {children}
        </GoogleOAuthProvider>
        </UserProvider>
      </body>
    </html>
  );
}
