# Generated by Django 5.1.4 on 2025-05-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='itinerary',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='places',
            field=models.JSONField(null=True),
        ),
    ]
