# Generated by Django 5.1.4 on 2025-05-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_trip_itinerary_alter_trip_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
