# Generated by Django 5.1.4 on 2025-05-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_trip_email_trip_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trip',
            table='Trips',
        ),
    ]
