# Generated by Django 5.1.4 on 2025-05-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_remove_trip_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='email',
            field=models.CharField(default='noemail@emample.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='username',
            field=models.CharField(default='noemail', max_length=100),
            preserve_default=False,
        ),
    ]
