# Generated by Django 5.1.4 on 2025-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_alter_trip_email_alter_trip_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='preferences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
